# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8b95db3abdc4719142cf30c3fba9b6c3698c6268255cd00aa4b6a951de967950a9494994a978f9c2ad0d25eafd34878645cd18d671aae9dc9c70677d0f22002

test:
  secret_key_base: be06860676d32e1b64b42014b4447817cca34f0518e4ac651d6e9ee216f7ec54e81a2d9e0953c8d255b442ddc53aa369f2b2f4389ee8ca236cd3fb936d1e55dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
