# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8586c4dbf6fa4b8a62c4a62eaf26ff045a7ca33c8e9b3b2177f6cbc8a1236531a3d7fa57f1ccb58871fdf7d1a4ce02f248b2c31461fca88286cc3d829422ab6f

test:
  secret_key_base: d44689c035d161b400c8a6c274212a947a2af5d97c826aae6fec01f69baa82f9d8bd03cc356a47006fed0e42baa8fd47e9ccbf6811256eeedb75127498092ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
