# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8273224c37e48718c450c9c47dfd8d1179bb208d86cf0a1b9a63c3b95943971113372d8c21417b18658931eea3c7a94047ba36a6c544c059c5ca659c9d6aa14

test:
  secret_key_base: 03f22a9d62b1b491d67fda5a77b1b6593f097d465166d2272358c60f082aedc2bb29f8265d7e63cb6d95b3723671e68be1e76064481eccf234523602fe58f7e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
