# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a21c6ca007fc088b33f62d90f5a278b022983f7726b862c26ec0d07b72216db264e0e2497982fa61635bc23aa735e84e03d48d09a3e14c6ca32b5b21ea665965

test:
  secret_key_base: a7c3debe54605d90b553a977f7d98c32c3f7cfea3dffd9be30ba6d3478fe9a3977a8138a9f5bb77b64784f4a4cb394047435e32b288f35a63633d42851786fb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
